--------------------------------------------------------
--  File created - Monday-March-18-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CATEGORIES
--------------------------------------------------------

  CREATE TABLE "AHMED"."CATEGORIES" 
   (	"ID" NUMBER(*,0), 
	"NAME" VARCHAR2(128 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ITEMS
--------------------------------------------------------

  CREATE TABLE "AHMED"."ITEMS" 
   (	"ID" NUMBER(*,0), 
	"AMOUNT" FLOAT(126) DEFAULT 0, 
	"NAME" VARCHAR2(20 BYTE), 
	"REPORT_ID" NUMBER(*,0), 
	"CATEGORY_ID" NUMBER(*,0), 
	"RECIEPT_IMG" VARCHAR2(512 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table REPORTS
--------------------------------------------------------

  CREATE TABLE "AHMED"."REPORTS" 
   (	"ID" NUMBER(*,0), 
	"TOTAL_AMOUNT" FLOAT(126) DEFAULT 0, 
	"APPROVAL_STATUS" VARCHAR2(20 BYTE), 
	"USER_ID" NUMBER(*,0), 
	"DESCRIPTION" VARCHAR2(512 BYTE), 
	"NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "AHMED"."USERS" 
   (	"ID" NUMBER(*,0), 
	"USERNAME" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"ROLE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into AHMED.CATEGORIES
SET DEFINE OFF;
Insert into AHMED.CATEGORIES (ID,NAME) values (1,'Travel Expenses');
Insert into AHMED.CATEGORIES (ID,NAME) values (2,'Meals and Entertainment');
Insert into AHMED.CATEGORIES (ID,NAME) values (3,'Office Supplies');
Insert into AHMED.CATEGORIES (ID,NAME) values (4,'Communication Expenses');
Insert into AHMED.CATEGORIES (ID,NAME) values (5,'Conference and Training');
Insert into AHMED.CATEGORIES (ID,NAME) values (6,'Corporate Events');
Insert into AHMED.CATEGORIES (ID,NAME) values (7,'Transportation');
Insert into AHMED.CATEGORIES (ID,NAME) values (8,'Accommodations');
Insert into AHMED.CATEGORIES (ID,NAME) values (9,'Miscellaneous Expenses');
REM INSERTING into AHMED.ITEMS
SET DEFINE OFF;
Insert into AHMED.ITEMS (ID,AMOUNT,NAME,REPORT_ID,CATEGORY_ID,RECIEPT_IMG) values (3,500,'clothes',1,6,'ayhaga');
REM INSERTING into AHMED.REPORTS
SET DEFINE OFF;
Insert into AHMED.REPORTS (ID,TOTAL_AMOUNT,APPROVAL_STATUS,USER_ID,DESCRIPTION,NAME) values (1,500,'pending',1,'ayhgaaa','paris trip');
REM INSERTING into AHMED.USERS
SET DEFINE OFF;
Insert into AHMED.USERS (ID,USERNAME,PASSWORD,ROLE) values (1,'ahmedashraf','1234','employee');
Insert into AHMED.USERS (ID,USERNAME,PASSWORD,ROLE) values (2,'ahmed','1234','manager');
--------------------------------------------------------
--  DDL for Index CATEGORIES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AHMED"."CATEGORIES_PK" ON "AHMED"."CATEGORIES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ITEMS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AHMED"."ITEMS_PK" ON "AHMED"."ITEMS" ("ID", "REPORT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index REPORTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AHMED"."REPORTS_PK" ON "AHMED"."REPORTS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index USERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AHMED"."USERS_PK" ON "AHMED"."USERS" ("ID", "USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index USERS_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "AHMED"."USERS_UK1" ON "AHMED"."USERS" ("USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CATEGORIES
--------------------------------------------------------

  ALTER TABLE "AHMED"."CATEGORIES" ADD CONSTRAINT "CATEGORIES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AHMED"."CATEGORIES" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "AHMED"."CATEGORIES" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ITEMS
--------------------------------------------------------

  ALTER TABLE "AHMED"."ITEMS" ADD CONSTRAINT "ITEMS_PK" PRIMARY KEY ("ID", "REPORT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AHMED"."ITEMS" MODIFY ("CATEGORY_ID" NOT NULL ENABLE);
  ALTER TABLE "AHMED"."ITEMS" MODIFY ("REPORT_ID" NOT NULL ENABLE);
  ALTER TABLE "AHMED"."ITEMS" MODIFY ("AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "AHMED"."ITEMS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REPORTS
--------------------------------------------------------

  ALTER TABLE "AHMED"."REPORTS" ADD CONSTRAINT "ID" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AHMED"."REPORTS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "AHMED"."REPORTS" MODIFY ("APPROVAL_STATUS" NOT NULL ENABLE);
  ALTER TABLE "AHMED"."REPORTS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "AHMED"."USERS" ADD CONSTRAINT "USERS_UK1" UNIQUE ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AHMED"."USERS" ADD CONSTRAINT "USERS_PK" PRIMARY KEY ("ID", "USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AHMED"."USERS" MODIFY ("ROLE" NOT NULL ENABLE);
  ALTER TABLE "AHMED"."USERS" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "AHMED"."USERS" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "AHMED"."USERS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ITEMS
--------------------------------------------------------

  ALTER TABLE "AHMED"."ITEMS" ADD CONSTRAINT "FK_ITEMS_CATEGORY" FOREIGN KEY ("CATEGORY_ID")
	  REFERENCES "AHMED"."CATEGORIES" ("ID") ENABLE;
  ALTER TABLE "AHMED"."ITEMS" ADD CONSTRAINT "FK_ITEMS_REPORTS" FOREIGN KEY ("REPORT_ID")
	  REFERENCES "AHMED"."REPORTS" ("ID") ENABLE;
